OUTPUT_ROOT: trackletpair_connectivity
DIST_BACKEND: 'nccl'
PI: 'acc'
WORKERS: 4
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  ROOT: '/mnt/ht/students/cmf/TNT_pytorch/data/crop_data'
  IMG_NUM_PER_GPU: 4
  MEAN: [102.9801, 115.9465, 122.7717]
  STD: [1, 1, 1]
MODEL:
  FILE: tracklet_connectivity
  NAME: TrackletConnectivity
  CONNECTIVITY:
    KERNEL_SIZE: [3, 5, 9, 13]
    FEAT_CHANNELS: [16, 64, 128]
    STACK_NUM: 3
  APPEARANCE:
    WEIGHTS: '/mnt/cephfs_new_wj/cv/chenmingfei.lasia/TNT_pytorch/work_dirs/facenet_triplet_appearance/2020-02-24-11-40/InceptionResnetV1_epoch012_iter001500_checkpoint.pth'
TRACKLET:
  WINDOW_lEN: 64
TRAIN:
  LR: 0.0001
  LR_FACTOR: 0.1
  WEIGHT_DECAY: 0.0005
  LR_STEPS: [4000, 8000] # paper TNT 5.2
  MAX_ITERATIONS: 10000
  OPTIMIZER: adam
  RESUME: True
  INPUT_MIN: 182
  INPUT_MAX: 182 
  PRINT_FREQ: 20 
  SAVE_INTERVAL: 500
  SAVE_EVERY_CHECKPOINT: True
  VAL_WHEN_TRAIN: True
TEST:
  TEST_SIZE: (182, 182) # min_size, max_size
  OUT_DIR: 'output'





